const data = [
    {
    id: '1',
    name: 'Dr. Jessi DiTillio',
    location: 'Los Angeles, California',
    role:'Co-founding Co-director',
    website:'https://www.jessiditillio.com/',
    instagram:'',
    image: require("./../img/logos/01.png"),
    },
    {
      id: '2',
      name: 'Katherine Spinella',
      location: 'Portland, Oregon',
      role:'Co-founding Co-director',
      website:'https://www.katherinespinella.com/',
      instagram:'',
      image: require("./../img/logos/01.png"),
    },
    {
      id: '3',
      name: 'Michael E. Stephen',
      location: 'Los Angeles, California',
      role:'Co-founding Co-director',
      website:'https://www.michaelestephen.com/',
      instagram:'',
      image: require("./../img/logos/01.png"),
    },
    {
      id: '4',
      name: 'John Whitten',
      location: 'Portland, Oregon',
      role:'Co-founding Co-director',
      website:'https://www.johnwhitten.com/',
      instagram:'',
      image: require("./../img/logos/01.png"),
      },
      {
        id: '5',
        name: 'Ashlin Aronin',
        location: 'Portland, Oregon',
        role:'Member since 2020',
        website:'https://ashlin.me/',
        instagram:'https://www.instagram.com/scenicbanker/?hl=en',
        image: require("./../img/logos/01.png"),
      },
      {
        id: '6',
        name: 'Rosana Aviña-Beam',
        location: 'Dallas, Texas',
        role:'Member since 2018',
        website:'',
        instagram:'',
        image: require("./../img/logos/01.png"),
      },
      {
        id: '7',
        name: 'Robert Collier Beam',
        location: 'Dallas, Texas',
        role:'Member since 2018',
        website:'',
        instagram:'',
        image: require("./../img/logos/01.png"),
      },
      {
        id: '8',
        name: 'Kristin Hough',
        location:'Reno, Nevada',
        role:'Member since 2020',
        website:'http://www.kristinhough.com/',
        instagram:'https://www.instagram.com/keekshough/?hl=en',
        image: require("./../img/logos/01.png"),
      },
      {
        id: '9',
        name: 'Morgan Rosskopf',
        location: 'Portland, Oregon',
        role:'Member since 2020',
        website:'http://morganrosskopf.com/',
        instagram:'https://www.instagram.com/morgan_rosskopf/',
        image: require("./../img/logos/01.png"),
      },
    ]
  

export default data;