const data = {
  artists: [
    {
    id: '1',
    name: 'Dr. Jessi DiTillio',
    location: 'Los Angeles, California',
    role:'Co-founding Co-director',
    website:'',
    instagram:'',
    image: require("./../Shop/img/book_01.jpg"),
    },
    {
      id: '2',
      name: 'Katherine Spinella',
      location: 'Portland, Oregon',
      role:'Co-founding Co-director',
      website:'',
      instagram:'',
      image: require("./../Shop/img/book_prints_set_01.jpg"),
    },
    {
      id: '3',
      name: 'Michael E. Stephen',
      location: 'Los Angeles, California',
      role:'Co-founding Co-director',
      website:'',
      instagram:'',
      image: require("./../Shop/img/salt_01.jpg"),
    },
    {
      id: '4',
      name: 'John Whitten',
      location: 'Portland, Oregon',
      role:'Co-founding Co-director',
      website:'',
      instagram:'',
      image: require("./../Shop/img/cloud-shirt_black.jpg"),
      },
      {
        id: '5',
        name: 'Ashlin Aronin',
        location: 'Portland, Oregon',
        role:'Member since 2020',
        website:'https://ashlin.me/',
        instagram:'https://www.instagram.com/scenicbanker/?hl=en',
        image: require("./../Shop/img/cloud-shirt_blue.jpg"),
      },
      {
        id: '6',
        name: 'Rosana Aviña-Beam',
        location: 'Dallas, Texas',
        role:'Member since 2018',
        website:'',
        instagram:'',
        image: require("./../Shop/img/spirit_lake_01.jpg"),
      },
      {
        id: '7',
        name: 'Robert Collier Beam',
        location: 'Dallas, Texas',
        role:'Member since 2018',
        website:'',
        instagram:'',
        image: require("./../Shop/img/cabin_01.jpg"),
      },
      {
        id: '8',
        name: 'Kristin Hough',
        location:'Reno, Nevada',
        role:'Member since 2020',
        website:'http://www.kristinhough.com/',
        instagram:'https://www.instagram.com/keekshough/?hl=en',
        image: require("./../Shop/img/cabin-interior_01.jpg"),
      },
      {
        id: '9',
        name: 'Morgan Rosskopf',
        location: 25,
        role:'Member since 2020',
        website:'http://morganrosskopf.com/',
        instagram:'https://www.instagram.com/morgan_rosskopf/',
        image: require("./../Shop/img/vla_01.jpg"),
      },
  ],
};

export default data;